version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn run build
artifacts:
  files:
    - "*/"
